# Default values for nginx-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
domain: gw.skymavis.xyz

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.15-alpine"

service:
  type: ClusterIP
  port: 80

hosts:
  - name: us
  - name: eu

