apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-chart2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-chart2
  template:
    metadata:
      labels:
        name: nginx-chart2
    spec:
      volumes:
        - name: html
          configMap:
            name: {{ (index .Values.hosts 1).name }}-cm
      containers:
        - name: {{ (index .Values.hosts 1).name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/
          ports:
            - name: https
              containerPort: 4443