apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  namespace: test
spec:
  rules:
    - host: {{ (index .Values.hosts 0).name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: http
                port:
                  number: 8080
    - host: {{ (index .Values.hosts 1).name }}.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: https
                port:
                  number: 4443
