apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: test
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    name: nginx-chart1

---

apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: test
spec:
  ports:
    - port: 4443
      targetPort: 4443
      name: https
  selector:
    name: nginx-chart2
